#採取速度
execute if score @s status.speed matches 5 run dialogue open @e[c=1,type=npc] @s speed_5
execute if score @s status.speed matches 6 run dialogue open @e[c=1,type=npc] @s speed_6
execute if score @s status.speed matches 7 run dialogue open @e[c=1,type=npc] @s speed_7
execute if score @s status.speed matches 8 run dialogue open @e[c=1,type=npc] @s speed_8
execute if score @s status.speed matches 9 run dialogue open @e[c=1,type=npc] @s speed_9
execute if score @s status.speed matches 10 run dialogue open @e[c=1,type=npc] @s speed_10
execute if score @s status.speed matches 11 run dialogue open @e[c=1,type=npc] @s speed_11
execute if score @s status.speed matches 12 run dialogue open @e[c=1,type=npc] @s speed_12
execute if score @s status.speed matches 13 run dialogue open @e[c=1,type=npc] @s speed_13
execute if score @s status.speed matches 14 run dialogue open @e[c=1,type=npc] @s speed_14
execute if score @s status.speed matches 15 run dialogue open @e[c=1,type=npc] @s speed_15
execute if score @s status.speed matches 16 run dialogue open @e[c=1,type=npc] @s speed_16
execute if score @s status.speed matches 17 run dialogue open @e[c=1,type=npc] @s speed_17
execute if score @s status.speed matches 18 run dialogue open @e[c=1,type=npc] @s speed_18
execute if score @s status.speed matches 19 run dialogue open @e[c=1,type=npc] @s speed_19
execute if score @s status.speed matches 20 run dialogue open @e[c=1,type=npc] @s speed_20
execute if score @s status.speed matches 21 run dialogue open @e[c=1,type=npc] @s speed_21
execute if score @s status.speed matches 22 run dialogue open @e[c=1,type=npc] @s speed_22
execute if score @s status.speed matches 23 run dialogue open @e[c=1,type=npc] @s speed_23
execute if score @s status.speed matches 24 run dialogue open @e[c=1,type=npc] @s speed_24
execute if score @s status.speed matches 25 run dialogue open @e[c=1,type=npc] @s speed_25
execute if score @s status.speed matches 26 run dialogue open @e[c=1,type=npc] @s speed_26
execute if score @s status.speed matches 27 run dialogue open @e[c=1,type=npc] @s speed_27
execute if score @s status.speed matches 28 run dialogue open @e[c=1,type=npc] @s speed_28
execute if score @s status.speed matches 29 run dialogue open @e[c=1,type=npc] @s speed_29
execute if score @s status.speed matches 30 run dialogue open @e[c=1,type=npc] @s speed_30
execute if score @s status.speed matches 31 run dialogue open @e[c=1,type=npc] @s speed_31
execute if score @s status.speed matches 32 run dialogue open @e[c=1,type=npc] @s speed_32
execute if score @s status.speed matches 33 run dialogue open @e[c=1,type=npc] @s speed_33
execute if score @s status.speed matches 34 run dialogue open @e[c=1,type=npc] @s speed_34
execute if score @s status.speed matches 35 run dialogue open @e[c=1,type=npc] @s speed_35
execute if score @s status.speed matches 36 run dialogue open @e[c=1,type=npc] @s speed_36
execute if score @s status.speed matches 37 run dialogue open @e[c=1,type=npc] @s speed_37
execute if score @s status.speed matches 38 run dialogue open @e[c=1,type=npc] @s speed_38
execute if score @s status.speed matches 39 run dialogue open @e[c=1,type=npc] @s speed_39
execute if score @s status.speed matches 40 run dialogue open @e[c=1,type=npc] @s speed_40
execute if score @s status.speed matches 41 run dialogue open @e[c=1,type=npc] @s speed_41
execute if score @s status.speed matches 42 run dialogue open @e[c=1,type=npc] @s speed_42
execute if score @s status.speed matches 43 run dialogue open @e[c=1,type=npc] @s speed_43
execute if score @s status.speed matches 44 run dialogue open @e[c=1,type=npc] @s speed_44
execute if score @s status.speed matches 45 run dialogue open @e[c=1,type=npc] @s speed_45
execute if score @s status.speed matches 46 run dialogue open @e[c=1,type=npc] @s speed_46
execute if score @s status.speed matches 47 run dialogue open @e[c=1,type=npc] @s speed_47
execute if score @s status.speed matches 48 run dialogue open @e[c=1,type=npc] @s speed_48
execute if score @s status.speed matches 49 run dialogue open @e[c=1,type=npc] @s speed_49
execute if score @s status.speed matches 50 run dialogue open @e[c=1,type=npc] @s speed_50
execute if score @s status.speed matches 51 run dialogue open @e[c=1,type=npc] @s speed_51
execute if score @s status.speed matches 52 run dialogue open @e[c=1,type=npc] @s speed_52
execute if score @s status.speed matches 53 run dialogue open @e[c=1,type=npc] @s speed_53
execute if score @s status.speed matches 54 run dialogue open @e[c=1,type=npc] @s speed_54
execute if score @s status.speed matches 55 run dialogue open @e[c=1,type=npc] @s speed_55
execute if score @s status.speed matches 56 run dialogue open @e[c=1,type=npc] @s speed_56
execute if score @s status.speed matches 57 run dialogue open @e[c=1,type=npc] @s speed_57
execute if score @s status.speed matches 58 run dialogue open @e[c=1,type=npc] @s speed_58
execute if score @s status.speed matches 59 run dialogue open @e[c=1,type=npc] @s speed_59
execute if score @s status.speed matches 60 run dialogue open @e[c=1,type=npc] @s speed_60
execute if score @s status.speed matches 61 run dialogue open @e[c=1,type=npc] @s speed_61
execute if score @s status.speed matches 62 run dialogue open @e[c=1,type=npc] @s speed_62
execute if score @s status.speed matches 63 run dialogue open @e[c=1,type=npc] @s speed_63
execute if score @s status.speed matches 64 run dialogue open @e[c=1,type=npc] @s speed_64
execute if score @s status.speed matches 65 run dialogue open @e[c=1,type=npc] @s speed_65
execute if score @s status.speed matches 66 run dialogue open @e[c=1,type=npc] @s speed_66
execute if score @s status.speed matches 67 run dialogue open @e[c=1,type=npc] @s speed_67
execute if score @s status.speed matches 68 run dialogue open @e[c=1,type=npc] @s speed_68
execute if score @s status.speed matches 69 run dialogue open @e[c=1,type=npc] @s speed_69
execute if score @s status.speed matches 70 run dialogue open @e[c=1,type=npc] @s speed_70
execute if score @s status.speed matches 71 run dialogue open @e[c=1,type=npc] @s speed_71
execute if score @s status.speed matches 72 run dialogue open @e[c=1,type=npc] @s speed_72
execute if score @s status.speed matches 73 run dialogue open @e[c=1,type=npc] @s speed_73
execute if score @s status.speed matches 74 run dialogue open @e[c=1,type=npc] @s speed_74
execute if score @s status.speed matches 75 run dialogue open @e[c=1,type=npc] @s speed_75
execute if score @s status.speed matches 76 run dialogue open @e[c=1,type=npc] @s speed_76
execute if score @s status.speed matches 77 run dialogue open @e[c=1,type=npc] @s speed_77
execute if score @s status.speed matches 78 run dialogue open @e[c=1,type=npc] @s speed_78
execute if score @s status.speed matches 79 run dialogue open @e[c=1,type=npc] @s speed_79
execute if score @s status.speed matches 80 run dialogue open @e[c=1,type=npc] @s speed_80
execute if score @s status.speed matches 81 run dialogue open @e[c=1,type=npc] @s speed_81
execute if score @s status.speed matches 82 run dialogue open @e[c=1,type=npc] @s speed_82
execute if score @s status.speed matches 83 run dialogue open @e[c=1,type=npc] @s speed_83
execute if score @s status.speed matches 84 run dialogue open @e[c=1,type=npc] @s speed_84
execute if score @s status.speed matches 85 run dialogue open @e[c=1,type=npc] @s speed_85
execute if score @s status.speed matches 86 run dialogue open @e[c=1,type=npc] @s speed_86
execute if score @s status.speed matches 87 run dialogue open @e[c=1,type=npc] @s speed_87
execute if score @s status.speed matches 88 run dialogue open @e[c=1,type=npc] @s speed_88
execute if score @s status.speed matches 89 run dialogue open @e[c=1,type=npc] @s speed_89
execute if score @s status.speed matches 90 run dialogue open @e[c=1,type=npc] @s speed_90
execute if score @s status.speed matches 91 run dialogue open @e[c=1,type=npc] @s speed_91
execute if score @s status.speed matches 92 run dialogue open @e[c=1,type=npc] @s speed_92
execute if score @s status.speed matches 93 run dialogue open @e[c=1,type=npc] @s speed_93
execute if score @s status.speed matches 94 run dialogue open @e[c=1,type=npc] @s speed_94
execute if score @s status.speed matches 95 run dialogue open @e[c=1,type=npc] @s speed_95
execute if score @s status.speed matches 96 run dialogue open @e[c=1,type=npc] @s speed_96
execute if score @s status.speed matches 97 run dialogue open @e[c=1,type=npc] @s speed_97
execute if score @s status.speed matches 98 run dialogue open @e[c=1,type=npc] @s speed_98
execute if score @s status.speed matches 99 run dialogue open @e[c=1,type=npc] @s speed_99
execute if score @s status.speed matches 100 run dialogue open @e[c=1,type=npc] @s speed_100