tellraw @s {"rawtext":[{"text":"§a採取§f "},{"score":{"name":"c.get","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§aリクエスト§f "},{"score":{"name":"c.requestClear","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§a庭§f "},{"score":{"name":"c.fw1","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§a草原§f "},{"score":{"name":"c.fw2","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§a湿地§f "},{"score":{"name":"c.fw3","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§a砂浜§f "},{"score":{"name":"c.fw4","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§a渓流§f "},{"score":{"name":"c.fw5","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§a山§f "},{"score":{"name":"c.fw6","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§a洞窟§f "},{"score":{"name":"c.fw7","objective":"World"}}]}
tellraw @s {"rawtext":[{"text":"§aゲームクリア§f "},{"score":{"name":"c.storyClear","objective":"World"}}]}
#tellraw @s {"rawtext":[{"text":"§a§f "},{"score":{"name":"","objective":"World"}}]}